apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibestream-app
spec:
  replicas: 1
  timeoutSeconds: 600
  selector:
    matchLabels:
      app: vibestream
  template:
    metadata:
      labels:
        app: vibestream
    spec:
      containers:
      - name: vibestream
        image: manishthaduri26/devops-demo:latest
        imagePullPolicy: Always  # Critical for CD: Always check for updates
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
